export interface UserBasic {
    userId:string,
    username:string,
    first_name:string,
    middle_initial:string,
    last_name:string,
    // dob:Date,
    // street_address:string,
    // apt:string,
    // city:string,
    // state:string,
    // zipcode:number,
    // billing_street_address: string,
    // billing_apt:string,
    // billing_city:string,
    // billing_state:string,
    // billing_zipcode:number,
    // fullName:string,
    // cardNo:number,
    // card_expiry:string,
};
